CustoFuncionarioApp/Models/Custo.cs
namespace CustoFuncionarioApp.Models
{
    public class Custo
    {
        public decimal SalarioBruto { get; set; }
        public decimal PlanoSaude { get; set; }
        public decimal SeguroVida { get; set; }
        public decimal OutrosBeneficios { get; set; }

        /*
            Calculado com base no salário:
            Até R$ 1.412,00	---> 7,5%
            De R$ 1.412,01 até R$ 2.666,68	---> 9%
            De R$ 2.666,69 até R$ 4.000,03	---> 12%
            De R$ 4.000,04 até R$ 7.786,02	---> 14%
            Acima disso, desconto fixo de R$ 908,85 ---> 0%
         */
        public decimal getINSS_Aliquota()
        {
            if (SalarioBruto <= 1412.00M) return 7.5M;
            if (SalarioBruto >=1412.01M && SalarioBruto <= 2666.68M) return 9M;
            if (SalarioBruto >= 2666.69M && SalarioBruto <= 4000.03M) return 12M;
            if (SalarioBruto >= 4000.04M && SalarioBruto <= 7786.02M) return 14M;
            return 0M;
        }

        public decimal getINSS_Valor()
        {
            return this.SalarioBruto * this.getINSS_Aliquota();
        }

        // Calculado como sendo 8% sobre o salário
        public decimal getFGTS()
        {
            return this.SalarioBruto * 0.08M;
        }

        public decimal get13oSalario()
        {
            return this.SalarioBruto;
        }

        // Salário base + 1/3
        public decimal getFerias()
        {
            return this.SalarioBruto + this.SalarioBruto / 3;
        }

        // Calcula o percentual que um custo representa em relação ao custo total
        // Exemplo: De todos os custos, qtos % são referentes a FGTS?
        public decimal getPercentualDespesa(decimal valorDespesa)
        {
            return (valorDespesa / this.getCustoTotal()) * 100;
        }

        public decimal getCustoTotal()
        {
            return this.SalarioBruto +
                   this.getINSS_Valor() +
                   this.getFGTS() +
                   this.get13oSalario() +
                   this.getFerias() +
                   this.PlanoSaude +
                   this.SeguroVida +
                   this.OutrosBeneficios;
        }
    }
}

CustoFuncionarioApp/Models/ErrorViewModel.cs
namespace CustoFuncionarioApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CustoFuncionarioApp/Controllers/CalculoController.cs
using CustoFuncionarioApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging.Abstractions;
using System.Drawing;

namespace CustoFuncionarioApp.Controllers
{
    public class CalculoController : Controller
    {
        private NullLogger<CalculoController> nullLogger;

        public CalculoController()
        {
        }

        public CalculoController(NullLogger<CalculoController> nullLogger)
        {
            this.nullLogger = nullLogger;
        }

        public IActionResult Relatorio(Custo custo)
        {
            return View(custo);
        }

        public async Task Relatorio(float valor)
        {
            throw new NotImplementedException();
        }
    }
}

CustoFuncionarioApp/Controllers/HomeController.cs
using CustoFuncionarioApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CustoFuncionarioApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CustoFuncionarioApp/Views/Calculo/Relatorio.cshtml
@model CustoFuncionarioApp.Models.Custo;
@{
    ViewData["Title"] = "Relatório de Custos";
}

<div class="text-center">
    <h1 class="display-4 mb-4">Relatório de Custos</h1>

    <div class="col-sm-8 col-md-4 mx-md-auto">
        <p>
            <span class="fw-bold">Salário Bruto: </span> R$
            @Model.SalarioBruto.ToString("N2")            
        </p>
        <p>
            <span class="fw-bold">INSS: </span> R$
            @Model.getINSS_Valor().ToString("N2")
        </p>
        <p>
            <span class="fw-bold">FGTS: </span> R$
            @Model.getFGTS().ToString("N2")
        </p>
        <p>
            <span class="fw-bold">13º Salário: </span> R$
            @Model.get13oSalario().ToString("N2")
        </p>
        <p>
            <span class="fw-bold">Férias: </span> R$
            @Model.getFerias().ToString("N2")
        </p>
        <p>
            <span class="fw-bold">Plano de Saúde: </span> R$
            @Model.PlanoSaude.ToString("N2")
        </p>
        <p>
            <span class="fw-bold">Seguro de Vida: </span> R$
            @Model.SeguroVida.ToString("N2")
        </p>
        <p>
            <span class="fw-bold">Outros Benefícios: </span> R$
            @Model.OutrosBeneficios.ToString("N2")
        </p>
        <hr />
        <p>
            <span class="fw-bold">Custo Total: </span> R$
            @Model.getCustoTotal().ToString("N2")
        </p>
        <hr />
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <div class="col-sm-8 col-md-4 mx-md-auto">
        <canvas id="myPieChart" width="250" height="250"></canvas>
        <script>
            var salarioBruto = @Html.Raw(Json.Serialize(Model.SalarioBruto));
            var inss = @Html.Raw(Json.Serialize(Model.getINSS_Valor()));
            var fgts = @Html.Raw(Json.Serialize(Model.getFGTS()));
            var decimoTerc = @Html.Raw(Json.Serialize(Model.get13oSalario()));
            var ferias = @Html.Raw(Json.Serialize(Model.getFerias()));
            var planoSaude = @Html.Raw(Json.Serialize(Model.PlanoSaude));
            var seguroVida = @Html.Raw(Json.Serialize(Model.SeguroVida));
            var outrosBeneficios = @Html.Raw(Json.Serialize(Model.OutrosBeneficios));
            var ctx = document.getElementById('myPieChart').getContext('2d');
            var myPieChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: ['Salário Bruto', 'INSS', 'FGTS', '13º Salário', 'Férias', 'Plano de Saúde', 'Seguro de Vida', 'Outros Benefícios'],
                    datasets: [{
                        data: [salarioBruto, inss, fgts, decimoTerc, ferias, planoSaude, seguroVida, outrosBeneficios],
                    }]
                },
                options: {
                    responsive: true
                }
            });
        </script>
    </div>
</div>

CustoFuncionarioApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 mb-4">Calculadora de Custos</h1>
    <form>
        <div class="col-4 m-auto mb-2 text-start">
            <div>
                <label for="SalarioBruto">Salário Bruto</label>
            </div>
            <div>
                <input name="SalarioBruto" type="number" step=".01" placeholder="0,00" class="w-100 text-end" />
            </div>            
        </div>
        <div class="col-4 m-auto mb-2 text-start">
            <div>
                <label for="PlanoSaude">Plano de Saúde</label>
            </div>
            <div>
                <input name="PlanoSaude" type="number" step=".01" placeholder="0,00" class="w-100 text-end" />
            </div>
        </div>
        <div class="col-4 m-auto mb-2 text-start">
            <div>
                <label for="SeguroVida">Seguro de Vida</label>
            </div>
            <div>
                <input name="SeguroVida" type="number" step=".01" placeholder="0,00" class="w-100 text-end" />
            </div>
        </div>
        <div class="col-4 m-auto mb-2 text-start">
            <div>
                <label for="OutrosBeneficios">Outros Benefícios</label>
            </div>
            <div>
                <input name="OutrosBeneficios" type="number" step=".01" placeholder="0,00" class="w-100 text-end" />
            </div>
        </div>

        <button id="btnCalcular" asp-controller="Calculo" asp-action="Relatorio" class="btn-dark mt-3 px-4 py-2">Calcular</button>
    </form>
</div>

CustoFuncionarioApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustoFuncionarioApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CustoFuncionarioApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CustoFuncionarioApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Calculadora de Custos</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - CustoFuncionarioApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>